spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ksmyk.dev2000@gmail.com
    password: umijnrbhxagjqlmd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/kamil?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update