spring:
  profiles:
    active: 'dev'
  main:
    banner-mode: 'off'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ksmyk.dev2000@gmail.com
    password: umijnrbhxagjqlmd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  error:
    include-message: always
logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/pracaInz-%d{yyyy-MM-dd}.%i.log
      max-history: 50
      max-file-size: 500MB
  file:
    path: ./logs
    name: ${logging.file.path}/prazaInz.log